import {useEffect,useState} from "react";
import {Alert,Pressable,StyleSheet,Switch,Text,TextInput,View} from "react-native";
import * as Location from "expo-location";
import {createUserWithEmailAndPassword,onAuthStateChanged,signInWithEmailAndPassword} from "firebase/auth";
import {collection,doc,onSnapshot,query,where} from "firebase/firestore";
import {httpsCallable} from "firebase/functions";
import {auth,db,functions} from "../lib/firebase";
type Offer={id:string;rideId?:string;serviceId?:string;serviceType:"RIDE"|"DELIVERY";distanceToPickupKm?:number;status:string};
type Service={status:string;estimatedFareCents?:number;destination?:{latitude:number;longitude:number}};
const rideNext:Record<string,string>={ACCEPTED:"DRIVER_ARRIVING",DRIVER_ARRIVING:"DRIVER_ARRIVED",DRIVER_ARRIVED:"TRIP_STARTED",TRIP_STARTED:"TRIP_COMPLETED"};
const deliveryNext:Record<string,string>={ACCEPTED:"GOING_TO_PICKUP",GOING_TO_PICKUP:"ARRIVED_PICKUP",ARRIVED_PICKUP:"PICKED_UP",PICKED_UP:"IN_DELIVERY",IN_DELIVERY:"ARRIVED_DESTINATION",ARRIVED_DESTINATION:"DELIVERED"};
const labels:Record<string,string>={DRIVER_ARRIVING:"A caminho do embarque",DRIVER_ARRIVED:"Cheguei ao embarque",TRIP_STARTED:"Corrida em andamento",TRIP_COMPLETED:"Corrida concluída",GOING_TO_PICKUP:"A caminho da coleta",ARRIVED_PICKUP:"Cheguei à coleta",PICKED_UP:"Pedido coletado",IN_DELIVERY:"Entrega em andamento",ARRIVED_DESTINATION:"Cheguei ao destino",DELIVERED:"Entrega concluída"};
export default function DriverHome(){
 const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[online,setOnline]=useState(false);const[busy,setBusy]=useState(false);const[authd,setAuthd]=useState(Boolean(auth.currentUser));const[offers,setOffers]=useState<Offer[]>([]);const[activeId,setActiveId]=useState<string|null>(null);const[activeType,setActiveType]=useState<"RIDE"|"DELIVERY"|null>(null);const[service,setService]=useState<Service|null>(null);
 useEffect(()=>onAuthStateChanged(auth,u=>setAuthd(Boolean(u))),[]);
 useEffect(()=>{if(!authd||!auth.currentUser){setOffers([]);return}const q=query(collection(db,"rideOffers"),where("driverId","==",auth.currentUser.uid),where("status","==","OFFERED"));const a=onSnapshot(q,s=>setOffers(s.docs.map(d=>({id:d.id,serviceType:"RIDE",...d.data()} as Offer))));const q2=query(collection(db,"serviceOffers"),where("courierId","==",auth.currentUser.uid),where("status","==","OFFERED"));const b=onSnapshot(q2,s=>setOffers(old=>[...old.filter(x=>x.serviceType!=="DELIVERY"),...s.docs.map(d=>({id:d.id,serviceType:"DELIVERY",serviceId:d.data().serviceId,...d.data()} as Offer))]));return()=>{a();b()}},[authd]);
 useEffect(()=>{if(!activeId||!activeType){setService(null);return}const coll=activeType==="RIDE"?"rides":"deliveries";return onSnapshot(doc(db,coll,activeId),s=>setService(s.exists()?s.data() as Service:null))},[activeId,activeType]);
 useEffect(()=>{if(!online||!auth.currentUser)return;let alive=true;const send=async()=>{if(!alive)return;try{const p=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High});await httpsCallable(functions,"updateDriverLocation")({latitude:p.coords.latitude,longitude:p.coords.longitude})}catch{}};void send();const timer=setInterval(send,10000);return()=>{alive=false;clearInterval(timer)}},[online]);
 async function login(){if(!email||password.length<6){Alert.alert("Dados inválidos","Informe e-mail e senha.");return}setBusy(true);try{try{await signInWithEmailAndPassword(auth,email.trim(),password)}catch{await createUserWithEmailAndPassword(auth,email.trim(),password)}await httpsCallable(functions,"ensureDriverProfile")({displayName:email.split("@")[0]})}catch(e){Alert.alert("SancaMobi",e instanceof Error?e.message:"Falha")}finally{setBusy(false)}}
 async function toggle(v:boolean){try{if(v){const p=await Location.requestForegroundPermissionsAsync();if(p.status!=="granted")throw new Error("Localização necessária.");const l=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High});await httpsCallable(functions,"setDriverAvailability")({online:true,latitude:l.coords.latitude,longitude:l.coords.longitude})}else await httpsCallable(functions,"setDriverAvailability")({online:false});setOnline(v)}catch(e){Alert.alert("Disponibilidade",e instanceof Error?e.message:"Falha")}}
 async function accept(o:Offer){try{if(o.serviceType==="RIDE"){await httpsCallable(functions,"acceptRide")({rideId:o.rideId});setActiveId(o.rideId||null)}else{await httpsCallable(functions,"acceptDelivery")({deliveryId:o.serviceId});setActiveId(o.serviceId||null)}setActiveType(o.serviceType);setOffers(x=>x.filter(y=>y.id!==o.id))}catch(e){Alert.alert("Oferta",e instanceof Error?e.message:"Indisponível")}}
 async function advance(){if(!activeId||!activeType||!service)return;const next=(activeType==="RIDE"?rideNext:deliveryNext)[service.status];if(!next)return;setBusy(true);try{await httpsCallable(functions,activeType==="RIDE"?"updateRideStatus":"updateDeliveryStatus")({[activeType==="RIDE"?"rideId":"deliveryId"]:activeId,status:next});if(next==="TRIP_COMPLETED"||next==="DELIVERED")Alert.alert("Concluído","Serviço finalizado.")}catch(e){Alert.alert("Serviço",e instanceof Error?e.message:"Falha")}finally{setBusy(false)}}
 async function cancel(){if(!activeId||!activeType)return;try{await httpsCallable(functions,activeType==="RIDE"?"updateRideStatus":"updateDeliveryStatus")({[activeType==="RIDE"?"rideId":"deliveryId"]:activeId,status:"CANCELLED"});setActiveId(null);setActiveType(null)}catch(e){Alert.alert("Serviço",e instanceof Error?e.message:"Falha")}}
 if(!authd)return <View style={s.auth}><Text style={s.logo}>SancaMobi</Text><Text style={s.subtitle}>Motorista + Entregador</Text><TextInput style={s.input} placeholder="E-mail" autoCapitalize="none" value={email} onChangeText={setEmail}/><TextInput style={s.input} placeholder="Senha" secureTextEntry value={password} onChangeText={setPassword}/><Pressable style={s.primary} onPress={login}><Text style={s.primaryText}>{busy?"Entrando...":"Entrar / Criar conta"}</Text></Pressable></View>;
 return <View style={s.container}><View style={s.header}><View><Text style={s.brand}>SancaMobi Pro</Text><Text style={s.small}>Motorista e Entregador</Text></View><Pressable onPress={()=>auth.signOut()}><Text>Sair</Text></Pressable></View><View style={s.card}><View style={s.row}><View><Text style={s.title}>Disponível para corridas e entregas</Text><Text style={s.small}>O sistema escolhe ofertas conforme sua habilitação.</Text></View><Switch value={online} onValueChange={toggle}/></View></View>{activeId&&service&&activeType?<View style={s.card}><Text style={s.badge}>{activeType==="RIDE"?"CORRIDA":"ENTREGA"}</Text><Text style={s.title}>{labels[service.status]||service.status}</Text><Text style={s.fare}>R$ {((service.estimatedFareCents||0)/100).toFixed(2)}</Text>{(activeType==="RIDE"?rideNext:deliveryNext)[service.status]&&<Pressable style={s.primary} onPress={advance} disabled={busy}><Text style={s.primaryText}>Avançar serviço</Text></Pressable>}{["ACCEPTED","DRIVER_ARRIVING","DRIVER_ARRIVED","GOING_TO_PICKUP","ARRIVED_PICKUP","PICKED_UP","IN_DELIVERY"].includes(service.status)&&<Pressable style={s.secondary} onPress={cancel}><Text>Cancelar</Text></Pressable>}</View>:<View style={s.card}><Text style={s.title}>Ofertas disponíveis</Text>{offers.length===0?<Text style={s.small}>Nenhuma oferta agora.</Text>:offers.map(o=><View style={s.offer} key={o.id}><View style={{flex:1}}><Text style={s.offerTitle}>{o.serviceType==="RIDE"?"🚗 Nova corrida":"📦 Nova entrega"}</Text><Text style={s.small}>{Number(o.distanceToPickupKm||0).toFixed(1)} km até a coleta</Text></View><Pressable style={s.accept} onPress={()=>accept(o)}><Text style={s.primaryText}>Aceitar</Text></Pressable></View>)}</View>}</View>
}
const s=StyleSheet.create({container:{flex:1,padding:20,paddingTop:60,gap:14,backgroundColor:"#f4f5f7"},auth:{flex:1,justifyContent:"center",padding:24,gap:14,backgroundColor:"#f4f5f7"},logo:{fontSize:38,fontWeight:"900",textAlign:"center"},subtitle:{textAlign:"center",fontSize:17},brand:{fontSize:24,fontWeight:"900"},small:{fontSize:13,color:"#666"},header:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},card:{backgroundColor:"#fff",borderRadius:20,padding:18,gap:12},row:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},title:{fontSize:18,fontWeight:"800"},input:{borderWidth:1,borderColor:"#ddd",borderRadius:12,padding:14,backgroundColor:"#fff"},primary:{backgroundColor:"#111",padding:15,borderRadius:14,alignItems:"center"},primaryText:{color:"#fff",fontWeight:"800"},secondary:{borderWidth:1,borderColor:"#ddd",padding:14,borderRadius:14,alignItems:"center"},badge:{fontSize:12,fontWeight:"900"},fare:{fontSize:26,fontWeight:"900"},offer:{flexDirection:"row",alignItems:"center",gap:12,borderTopWidth:1,borderTopColor:"#eee",paddingTop:12},offerTitle:{fontWeight:"800"},accept:{backgroundColor:"#111",padding:11,borderRadius:11}});
