import {useEffect,useMemo,useState} from "react";
import {Alert,Pressable,StyleSheet,Text,TextInput,View} from "react-native";
import MapView,{Marker} from "react-native-maps";
import * as Location from "expo-location";
import {createUserWithEmailAndPassword,onAuthStateChanged,signInWithEmailAndPassword} from "firebase/auth";
import {doc,onSnapshot} from "firebase/firestore";
import {httpsCallable} from "firebase/functions";
import {auth,db,functions} from "../lib/firebase";
type Coord={latitude:number;longitude:number}; type PaymentMethod="PIX"|"CREDIT_CARD"|"DEBIT_CARD"|"GOOGLE_PAY"|"APPLE_PAY"; type Delivery={status:string;estimatedFareCents?:number;estimatedDistanceKm?:number;paymentStatus?:string;paymentMethod?:PaymentMethod;requestType?:string};
const home={latitude:-22.0175,longitude:-47.8908,latitudeDelta:.04,longitudeDelta:.04};
const labels:Record<string,string>={SEARCHING_COURIER:"Procurando entregador",OFFERED:"Acionando entregadores",ACCEPTED:"Entregador aceitou",GOING_TO_PICKUP:"Indo para coleta",ARRIVED_PICKUP:"No local de coleta",PICKED_UP:"Pedido coletado",IN_DELIVERY:"Em entrega",ARRIVED_DESTINATION:"Chegou ao destino",DELIVERED:"Entrega concluída",CANCELLED:"Entrega cancelada",NO_COURIER:"Nenhum entregador disponível"};
function hav(a:Coord,b:Coord){const R=6371,d1=(b.latitude-a.latitude)*Math.PI/180,d2=(b.longitude-a.longitude)*Math.PI/180;const x=Math.sin(d1/2)**2+Math.cos(a.latitude*Math.PI/180)*Math.cos(b.latitude*Math.PI/180)*Math.sin(d2/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
export default function StoreHome(){
 const[email,setEmail]=useState(""); const[paymentMethod]=useState<PaymentMethod>("PIX");const[password,setPassword]=useState("");const[name,setName]=useState("");const[authd,setAuthd]=useState(Boolean(auth.currentUser));const[busy,setBusy]=useState(false);const[pickup,setPickup]=useState<Coord|null>(null);const[destination,setDestination]=useState<Coord|null>(null);const[deliveryId,setDeliveryId]=useState<string|null>(null);const[delivery,setDelivery]=useState<Delivery|null>(null);const[message,setMessage]=useState("Escolha o destino no mapa.");
 useEffect(()=>onAuthStateChanged(auth,u=>setAuthd(Boolean(u))),[]);
 useEffect(()=>{if(!authd)return;(async()=>{const p=await Location.requestForegroundPermissionsAsync();if(p.status==="granted"){const l=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High});setPickup({latitude:l.coords.latitude,longitude:l.coords.longitude});}})()},[authd]);
 useEffect(()=>{if(!deliveryId){setDelivery(null);return}return onSnapshot(doc(db,"deliveries",deliveryId),s=>setDelivery(s.exists()?s.data() as Delivery:null))},[deliveryId]);
 const calc=useMemo(()=>pickup&&destination?{km:hav(pickup,destination),min:Math.max(3,Math.round(hav(pickup,destination)/25*60))}:null,[pickup,destination]);
 async function login(){if(password.length<6||!email){Alert.alert("Dados inválidos","Informe e-mail e senha.");return}setBusy(true);try{try{await signInWithEmailAndPassword(auth,email.trim(),password)}catch{await createUserWithEmailAndPassword(auth,email.trim(),password)}await httpsCallable(functions,"ensureStoreProfile")({displayName:name||email.split("@")[0]})}catch(e){Alert.alert("SancaMobi",e instanceof Error?e.message:"Falha")}finally{setBusy(false)}}
 async function create(){if(!pickup||!destination||!calc)return;setBusy(true);try{const r=await httpsCallable(functions,"createDelivery")({pickup,destination,estimatedDistanceKm:calc.km,estimatedDurationMin:calc.min,paymentMethod,requestType:"ON_DEMAND"});const d=r.data as {deliveryId:string;status:string};setDeliveryId(d.deliveryId);setMessage(labels[d.status]??d.status)}catch(e){Alert.alert("Entrega",e instanceof Error?e.message:"Falha")}finally{setBusy(false)}}
 async function pay(){if(!deliveryId)return;try{const r=await httpsCallable(functions,"createMercadoPagoPix")({serviceId:deliveryId,serviceType:"DELIVERY",paymentMethod});const d=r.data as {qrCode?:string;ticketUrl?:string;status:string};Alert.alert("Mercado Pago",d.qrCode?"Pix criado. Copie o código exibido.":"Pagamento "+d.status+". "+(d.ticketUrl||""))}catch(e){Alert.alert("Pagamento",e instanceof Error?e.message:"O entregador precisa conectar o Mercado Pago.")}}
 if(!authd)return <View style={s.auth}><Text style={s.logo}>SancaMobi</Text><Text style={s.subtitle}>Painel da Loja</Text><TextInput style={s.input} placeholder="Nome da loja" value={name} onChangeText={setName}/><TextInput style={s.input} placeholder="E-mail" autoCapitalize="none" value={email} onChangeText={setEmail}/><TextInput style={s.input} placeholder="Senha" secureTextEntry value={password} onChangeText={setPassword}/><Pressable style={s.primary} onPress={login}><Text style={s.primaryText}>{busy?"Entrando...":"Entrar / Criar loja"}</Text></Pressable></View>;
 return <View style={s.container}><MapView style={s.map} initialRegion={home} showsUserLocation onPress={e=>setDestination(e.nativeEvent.coordinate)}>{pickup&&<Marker coordinate={pickup} title="Coleta"/>}{destination&&<Marker coordinate={destination} title="Destino"/>}</MapView><View style={s.top}><View><Text style={s.brand}>SancaMobi Loja</Text><Text style={s.small}>Entrega avulsa · somente pagamento digital</Text></View><Pressable onPress={()=>auth.signOut()}><Text>Sair</Text></Pressable></View><View style={s.sheet}>{delivery?<><Text style={s.title}>{labels[delivery.status]||delivery.status}</Text><Text style={s.detail}>{delivery.estimatedDistanceKm?.toFixed(1)} km · R$ {((delivery.estimatedFareCents||0)/100).toFixed(2)}</Text><Text style={s.small}>Entrega avulsa · pagamento exclusivamente digital</Text><Text style={s.small}>Forma: {delivery.paymentMethod||paymentMethod}</Text><Text style={s.small}>Pagamento: {delivery.paymentStatus||"PENDING"}</Text>{delivery.paymentStatus!=="approved"&&delivery.paymentStatus!=="APPROVED"&&<Pressable style={s.primary} onPress={pay}><Text style={s.primaryText}>Pagar via Mercado Pago</Text></Pressable>}</>:<><Text style={s.title}>{message}</Text>{calc&&<><Text style={s.detail}>Estimativa: {calc.km.toFixed(1)} km · {calc.min} min</Text><Pressable style={s.primary} onPress={create}><Text style={s.primaryText}>{busy?"Solicitando...":"Solicitar entregador"}</Text></Pressable></>}</>}</View></View>
}
const s=StyleSheet.create({container:{flex:1,backgroundColor:"#f4f5f7"},map:{flex:1},auth:{flex:1,justifyContent:"center",padding:24,gap:12,backgroundColor:"#f4f5f7"},logo:{fontSize:38,fontWeight:"900",textAlign:"center"},subtitle:{textAlign:"center",fontSize:18},input:{backgroundColor:"#fff",borderWidth:1,borderColor:"#ddd",borderRadius:12,padding:14},top:{position:"absolute",top:50,left:14,right:14,padding:14,borderRadius:18,backgroundColor:"#fff",flexDirection:"row",justifyContent:"space-between"},brand:{fontSize:20,fontWeight:"900"},small:{fontSize:12,color:"#666"},sheet:{position:"absolute",left:12,right:12,bottom:20,padding:18,borderRadius:22,backgroundColor:"#fff",gap:10},title:{fontSize:18,fontWeight:"800"},detail:{fontSize:15,color:"#555"},primary:{backgroundColor:"#111",padding:15,borderRadius:14,alignItems:"center"},primaryText:{color:"#fff",fontWeight:"800"}});